# Generated by Django 5.0.1 on 2024-10-29 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, default='uz', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=6)),
                ('position', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=255)),
                ('marriage', models.BooleanField(default=False)),
                ('first_answer', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(max_length=255)),
                ('second_answer', models.TextField(blank=True, null=True)),
                ('convince', models.BooleanField(default=False)),
                ('driver_license', models.CharField(max_length=100)),
                ('has_car', models.BooleanField(default=False)),
                ('english_level', models.CharField(max_length=25)),
                ('russian_level', models.CharField(max_length=25)),
                ('other_language', models.CharField(max_length=255)),
                ('third_answer', models.CharField(max_length=25)),
                ('fourth_answer', models.CharField(max_length=25)),
                ('c1_program_level', models.CharField(max_length=25)),
                ('fifth_answer', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.botuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
