# Generated by Django 5.0.1 on 2024-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_remove_userrequest_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='sixth_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
