# Generated by Django 5.0.1 on 2024-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_botuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='worked_furniture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
