# Generated by Django 5.0.1 on 2024-10-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_userrequest_worked_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='worked_furniture',
            field=models.BooleanField(default=False),
        ),
    ]
