# Generated by Django 5.0.1 on 2024-10-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_alter_userrequest_worked_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='birth_year',
            field=models.CharField(max_length=255),
        ),
    ]
