# Generated by Django 5.0.1 on 2024-11-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_alter_userrequest_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='c1_program_level',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='position',
        ),
    ]
